name: Build main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
      with:
        repo-token: ${{ secrets.GIT_SECRET }}
    - name: Run CMake
      run: cmake -P {0}
    - name: Build & Tests
      run: make all test
