name: Build main

on: [push]

strategy:
  matrix:
    compiler: [gcc, clang]
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v1
    - name: Run CMake
      env:
        CC: ${{ matrix.compiler }}
      run: cmake -P {0}
