name: Build main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/googletest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/* /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a && sudo ln -s /usr/lib/libgmock.a /usr/local/lib/libgmock.a && sudo ln -s /usr/lib/libgmock_main.a /usr/local/lib/libgmock_main.a
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake .
    - name: Build & Tests
      run: make all test
