name: Build main

on: [push]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Run CMake
      run: cmake -P {0}
    - name: Build & Tests
      run: make all test
